# Generated by Django 5.0.7 on 2024-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_user_delete_taskmanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("mytask", models.TextField()),
            ],
        ),
    ]
